# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/azure/app-service/app-service-plan-manage#create-an-app-service-plan
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on: [push, pull_request]

env:
  RSG_NAME: rg-we-huureenarts-prod
  RSG_SECRETS_NAME: rg-we-huureenarts-secrets-prod
  DEFAULT_LOCATION: westeurope               # set this to the node version to use

jobs:
  deploy-env:
    name: deploy environment resources
    runs-on: ubuntu-latest
    steps:

    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: deploy resource group
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: 
          az group create -n ${{ env.RSG_NAME }} -l ${{ env.DEFAULT_LOCATION }}
          az group create -n ${{ env.RSG_SECRETS_NAME }} -l ${{ env.DEFAULT_LOCATION }}
        azcliversion: latest