# This workflow will build and push a node.js application to an Azure Web App when a release is created.
#
# This workflow assumes you have already created the target Azure App Service web app.
# For instructions see https://docs.microsoft.com/azure/app-service/app-service-plan-manage#create-an-app-service-plan
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
#    For instructions on obtaining the publish profile see: https://docs.microsoft.com/azure/app-service/deploy-github-actions#configure-the-github-secret
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
on: [push, pull_request]

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '10.x'                # set this to the node version to use

jobs:
  deploy-env:
    env:
      RSG_NAME: rg-we-huureenarts-prod
      RSG_SECRETS_NAME: rg-we-huureenarts-secrets-prod
      DEFAULT_LOCATION: westeurope
    name: deploy environment resources
    runs-on: ubuntu-latest
    steps:

    - name: deploy resource group
      uses: Azure/cli@v1.0.0
      with:
        # Specify the script here
        inlineScript: 
          az group create -n ${resourceGroupName} -l ${DEFAULT_LOCATION}
          az group create -n ${resourceGroupSecretsName} -l ${DEFAULT_LOCATION}
        azcliversion: latest
        env:
          RSG_NAME: ${{ jobs.deploy-env.env.RSG_NAME }}
          RSG_SECRETS_NAME: ${{ jobs.deploy-env.env.RSG_SECRETS_NAME }}
          DEFAULT_LOCATION: ${{ jobs.deploy-env.env.DEFAULT_LOCATION }}